#!/bin/bash

# Copyright (c) 2023-2024 Nakamura Musical Industries.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, 
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice, 
#    this list of conditions and the following disclaimer in the documentation 
#    and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its contributors 
#    may be used to endorse or promote products derived from this software 
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND 
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY 
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND 
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

updatepkg_version="20240910"

_aptonly="false"

# Translations
_lang=$(printenv LANG | grep -oP '.+(?=\.)')
if [[ ${_lang} == "ja_JP" ]]; then
	msg_root="rootで実行して下さい"
	msg_invalid_arg="不正なオプションです"
	msg_usage="使い方"
	msg_usage_options="オプション"
	msg_usage_y="「-y」の入力をスキップ"
	msg_usage_h="使い方を表示"
	msg_usage_v="バージョンを表示"
	msg_usage_a="APTのみ実行"
	msg_done="完了しました！"
else
	msg_root="Need to run as root!"
	msg_invalid_arg="Invalid argument"
	msg_usage="Usage"
	msg_usage_options="Options"
	msg_usage_y="Skip input '-y'"
	msg_usage_h="Show usage"
	msg_usage_v="Show version"
	msg_usage_a="Run APT only"
	msg_done="Done!"
fi

usage(){
	echo "${msg_usage}: updatepkg <options>"
	echo
	echo "${msg_usage_options}:"
	echo "   -y     ${msg_usage_y}"
	echo "   -a     ${msg_usage_a}"
	echo
	echo "   -h     ${msg_usage_h}"
	echo "   -v     ${msg_usage_v}"
}

main(){
	if [[ $(whoami) != "root" ]]; then
		echo ${msg_root}
		exit 1
	fi

	apt update
	apt upgrade ${_yes}
	apt autoremove ${_purge} ${_yes}

	if [[ ${_aptonly} != "true" ]]; then
		if [ $(command -v flatpak) ]; then
			flatpak update ${_yes}
		fi
	fi

	echo ${msg_done}
}

version(){
	echo
	echo "updatepkg v${updatepkg_version}"
	echo "Copyright (c) 2023-2024 Nakamura Musical Industries."
	echo
	echo "This program may be freely redistributed under"
	echo "the terms of the 3-clause BSD License."
	echo
}

while getopts 'havy' arg; do
	case ${arg} in
		h)
			usage
			exit 0
			;;
		a)
			_aptonly="true"
			shift 1
			;;
		v)
			version
			exit 0
			;;
		y)
			_yes="-y"
			shift 1
			;;
		*)
			usage
			exit 1
			;;
	esac
done

main
